services:
  # Frontend Service (Development)
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portfolio-network-dev

  # Backend Service (Development with hot reload)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "9229:9229"  # Debug port
    depends_on:
      - ai-service
    environment:
      - NODE_ENV=development
      - PORT=5000
      - AI_SERVICE_URL=http://ai-service:8000
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_TO=${EMAIL_TO}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/logs:/app/logs
    networks:
      - portfolio-network-dev
    restart: unless-stopped

  # AI Service (Development with hot reload)
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    volumes:
      - ./ai-service:/app
      - ./ai-service/logs:/app/logs
    networks:
      - portfolio-network-dev
    restart: unless-stopped

networks:
  portfolio-network-dev:
    driver: bridge
